### ISSUE TITLE
2. コマンドライン引数をprintするプログラムを作る

### ISSUE THREAD

**Issue by datsuns** [datsuns/yui_learning#1]
hello.c から hello という名前のプログラムを作ったとして、
以下を満たすプログラム作る。

* ビルドするコマンド：
   * 自分で解決できるかな？
* 実行方法：
   * `./hello command line params`
* 実行結果：
   * 「command line params」が表示される

**Comment by KuniakiY** [comment]
helloと表示するプログラムという認識で合ってますか？

**Comment by KuniakiY** [comment]
command line paramsと表示させればいいんですね！

**Comment by KuniakiY** [comment]
hello.cからhelloというプログラムを作るというのがイメージ沸かないです💦

**Comment by datsuns** [comment]
> helloと表示するプログラムという認識で合ってますか？
> command line paramsと表示させればいいんですね！

ちょっとおしい。
`コマンドライン引数`をちらっと調べてみて。
`hello.exe`を作ったとして、
`hello.exe command line params` と実行したなら、 `command line params`と表示されて、
`hello.exe a b c`と実行したなら、`a b c`と表示されることを期待してます。

**Comment by datsuns** [comment]
> hello.cからhelloというプログラムを作るというのがイメージ沸かないです💦

`hello.exe`の方が分かりやすいかな？
hello.c というソースコードをビルドして、 hello.exeを作る。

どう？

**Comment by KuniakiY** [comment]
int main(int argc,char* argv[])
{
    int i;
    
    for(i=0; i < argc, i++)
    {
       printf("%s",argv[i]);
    }
    return 0;

}

**Comment by datsuns** [comment]
そうそうそんなかんじ

**Comment by KuniakiY** [comment]
visual studio でhello.exeをさくせいしました。

**Comment by KuniakiY** [comment]
実行結果です。

C:\Users\kykyk>C:\Users\kykyk\Desktop\hello.exe a b c
C:\Users\kykyk\Desktop\hello.exeabc

**Comment by datsuns** [comment]
おけ。二点ほど。

1. 実行結果が正しいかどうかの判断結果も書いてくだされい
1. 次は黒い画面で頑張ってみよう

**Comment by KuniakiY** [comment]
1.は今日帰宅してから追記します。
2.についてですが、makefileを使って行うという認識で合ってますか？

**Comment by datsuns** [comment]
黒い画面は、必ずしもmakefileを使う必要は無いです。
では、入れたcygwinで直接`gcc4`を使ってビルドができます。

* `cd 作ったファイルのあるディレクトリ`
* `gcc4 hello.c`

とやってみましょう。
`hello.out`ていうファイルが出来上がるはずです。これは`./hello.out a b c`と実行できます。

あー、visual studioでのプロジェクトの作り方によって、上のコマンドではビルドできないかも。。

hello.cで`stdio.h`以外をincludeしてるかな？

**Comment by KuniakiY** [comment]
visual studioはやめてメモ帳で作りました。
gcc hello.c には成功しました。
gcc４は失敗しました。
hello.outというファイルはできていなさそうです・・・

**Comment by KuniakiY** [comment]
hello.c でstdio.h以外はincludeしていません。

**Comment by KuniakiY** [comment]
C:\Users\kykyk>C:\Users\kykyk\Desktop\hello.exe a b c
で、hello.exeを実行しています。
その中身はコマンドライン引数を出力するというもので、
実行したファイル名も含めるので、
出力結果の”hello.exeabc”は正しいです。

**Comment by datsuns** [comment]
> visual studioはやめてメモ帳で作りました。
> gcc hello.c には成功しました。
> gcc４は失敗しました。

一緒に画面見ながらやれてるわけじゃないので、もう少し詳しく教えてくだされ。

以下のコマンドの実行結果のログをここに貼り付けられる？画面に表示されるのを貼り付けて

* `gcc helloc`
* `gcc4 hello.c`

**Comment by datsuns** [comment]
> 出力結果の”hello.exeabc”は正しいです。

もうヒトコエ。各引数をスペース区切りで出せるかな？

```
# ./hello.exe a b c 
a b c
```
という風に。

**Comment by KuniakiY** [comment]
# Host: DESKTOP-CQ5DACG | User: kykyk | Time: 2016-12-20 19:53:08
 # Path: /c/Users/kykyk/Desktop
 # # gcc hello.c

 ✔ Success (retv = 0)

**Comment by datsuns** [comment]
thx.

てかそれgcc4が無い言うとるのか。。。
次はどうなる？

* `which gcc`
* `gcc --version`

**Comment by datsuns** [comment]
あとは`gcc`の方はコマンドが成功してるのにhello.outが無いのか。。

念のため、以下を試してもらえる？
（ひょっとしてhello.exeが出力されるかも知れんので、明示的にhello.outを出すような指定）

`gcc -o hello.out hello.c`

**Comment by KuniakiY** [comment]
# Host: DESKTOP-CQ5DACG | User: kykyk | Time: 2016-12-20 19:55:12
 # Path: /c/Users/kykyk/Desktop
 # # gcc -o hello.out hello.c

 ✔ Success (retv = 0)

来ました！！！
デスクトップにhello.outができてます！！！

**Comment by KuniakiY** [comment]
# Host: DESKTOP-CQ5DACG | User: kykyk | Time: 2016-12-20 20:10:46
 # Path: /c/Users/kykyk/Desktop
 # # ./hello.out a b c
./hello.outabc
 ✔ Success (retv = 0)
こっちもできてます！

**Comment by KuniakiY** [comment]
あとはスペース問題何とかします

**Comment by datsuns** [comment]
> デスクトップにhello.outができてます！！！

なるほど。。。なんか手元のgccと動きが違うが、、
まえっか。とりあえず`gcc`を使うのでいこう。

**Comment by datsuns** [comment]
> あとはスペース問題何とかします

見落とし一箇所ありました。

```
# ./hello.out a b c
./hello.outabc
```

これよく見ると、コマンドの名前も出てしまってるね？
「引数だけスペース区切りに出す」
で、いってみよう。

**Comment by KuniakiY** [comment]
# Host: DESKTOP-CQ5DACG | User: kykyk | Time: 2016-12-20 20:49:55
 # Path: /c/Users/kykyk/Desktop
 # # ./hello.out a b c
a b c
 ✔ Success (retv = 0)
やったりました！

**Comment by KuniakiY** [comment]
ソースコードです
#include "stdio.h"

int main(int argc, char* argv[])
{
	int i;
	for (i = 1; i < argc; i++)
	{
		printf("%s%c", argv[i], 0x20);
	}
	return 0;
}

**Comment by datsuns** [comment]
おけおけ！

**Comment by datsuns** [comment]
できてると判断したのでクローズ
