### ISSUE TITLE
3. プログラムをmakeでビルドできるようにする

### ISSUE THREAD

**Issue by datsuns** [datsuns/yui_learning#3]
https://github.com/datsuns/yui_learning/issues/1 で作ったプログラムをmakeでビルド出来るようにする

* makefile はこのチケットに添付したものを利用する
   * と思ったけど添付できなかったので最後に書くのでコピペしてくだされ
* hello.c と同じディレクトリにmakefileを置く
* ビルドするコマンド：
   * 自分で解決できるかな？
* 実行結果は https://github.com/datsuns/yui_learning/issues/1 と変わらない

makefileの内容

**hello.cを作ったのを前提にした内容です**

```make
.PHONY: default test

default: test

test: hello.out
	./hello.out command line params

hello.out: hello.o
	gcc -o $@ $<

hello.o: hello.c
	gcc -c -o $@ $<

```

**Comment by KuniakiY** [comment]
できました！

 # Host: DESKTOP-CQ5DACG | User: kykyk | Time: 2016-12-23 00:46:19
 # Path: /c/Users/kykyk/Desktop
 # # make -f GNUmakefile.txt
gcc -c -o hello.o hello.c
gcc -o hello.out hello.o
./hello.out command line params
command line params

**Comment by KuniakiY** [comment]
最後の行のcommand line paramsが出力結果ですね。

**Comment by datsuns** [comment]
おけ。いかてますね。クローズしときやす。
