### ISSUE TITLE
4. 作ったプログラムをgithubに放り込む

### ISSUE THREAD

**Issue by datsuns** [datsuns/yui_learning#4]
以下のコマンドで実施

* hello.cはどこか作業用のディレクトリを作ってそこに入れておきましょう
* `cd hello.cの場所`
* `git init`していない場合は以下実施（もししてたら`.git/`というディレクトリがあるはず。`ls -a`で確認できる）
   * `git init`
   * `git add .`
   * `git commit -m'initial'`
* `git remote add origin https://github.com/datsuns/yui_learning.git`
* `git push origin master`
* githubのアカウント、パスワードを入れる
* https://github.com/datsuns/yui_learning に作ったファイルが適用される

以降、何かやったら 
* `git add .`
* `git commit -m'任意のコメント'`
* `git push origin master` 
をやっておきましょう

各コマンドの意味はまた別途説明します

**Comment by KuniakiY** [comment]
# Host: DESKTOP-CQ5DACG | User: kykyk | Time: 2016-12-20 20:49:57
 # Path: /c/Users/kykyk/Desktop
 # # git init
Initialized empty Git repository in /c/Users/kykyk/Desktop/.git/

 ✔ Success (retv = 0)

 # Host: DESKTOP-CQ5DACG | User: kykyk | Time: 2016-12-21 18:49:09
 # Path: /c/Users/kykyk/Desktop
 # # git add .

 ✔ Success (retv = 0)

 # Host: DESKTOP-CQ5DACG | User: kykyk | Time: 2016-12-21 18:50:11
 # Path: /c/Users/kykyk/Desktop
 # # git commit -m'initial'

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'kykyk@DESKTOP-CQ5DACG.(none)')

 ✗ Failure (retv = 128)

 # Host: DESKTOP-CQ5DACG | User: kykyk | Time: 2016-12-21 18:50:32
 # Path: /c/Users/kykyk/Desktop
 # # git remote add origin https://github.com/datsuns/yui_learning.git

 ✔ Success (retv = 0)

 # Host: DESKTOP-CQ5DACG | User: kykyk | Time: 2016-12-21 18:51:36
 # Path: /c/Users/kykyk/Desktop
 # # git push origin master
error: src refspec master does not match any.
error: failed to push some refs to 'https://github.com/datsuns/yui_learning.git'

こうなりました。

**Comment by datsuns** [comment]
おけおけ。`git commit`が失敗してる。
`git commit`でのログにあるように、`git config user.name  名前`と`git config user.email  アドレス`をやりましょう
名前とアドレスはgithubのアカウントとあわせた方が良いよー。

で、そのあとは`git push`だけやり直せばおけ

**Comment by datsuns** [comment]
ちなみに黒い画面でのコマンドの実行には、「そのコマンドが失敗したかどうか？」ていう概念の情報があるんやけど、今使ってもらってるcygwinの機能で、コマンドを実行したあとに「success」とか「failure」とか出てね。
これ、failureて出たら失敗してまんねん

**Comment by KuniakiY** [comment]
$B$J$k$[$I!"$H$$$&$3$H$O(B
git commit -m'initial'
$B$H(B
git push origin master
$B$O<:GT$7$F$k$H$$$&$3$H$G$9$M!#(B

2016/12/22 9:06$B!"(Ban udon programmer <notifications@github.com<mailto:notifications@github.com>> $B$N%a%C%;!<%8(B:


$B$A$J$_$K9u$$2hLL$G$N%3%^%s%I$N<B9T$K$O!"!V$=$N%3%^%s%I$,<:GT$7$?$+$I$&$+!)!W$F$$$&35G0$N>pJs$,$"$k$s$d$1$I!":#;H$C$F$b$i$C$F$k(Bcygwin$B$N5!G=$G!"%3%^%s%I$r<B9T$7$?$"$H$K!V(Bsuccess$B!W$H$+!V(Bfailure$B!W$H$+=P$F$M!#(B
$B$3$l!"(Bfailure$B$F=P$?$i<:GT$7$F$^$s$M$s(B

-

**Comment by KuniakiY** [comment]
名前とアドレスは成功させました。
ログは今晩貼り付けます。

**Comment by KuniakiY** [comment]
git push はアドレス名前を打ち込んだ後もダメだった気が…
今晩そちらのログも貼り付けます。

**Comment by KuniakiY** [comment]
できました！
git commitでつまずいていたみたいですね。
何はともあれ、成功してよかったです。
それにしても、hello.c が入っているディレクトリ内の
ファイルすべてがcommitされてしまうんですね。
（へんな動画とか置いてなくてよかった・・・）

**Comment by datsuns** [comment]
おけ。

なので「ディレクトリ作ってそこに入れよう」て言うてたのよ。
まぁ気が向いたら直しておくわ

**Comment by datsuns** [comment]
ファイルの塩梅なおしておいたでー
以下のコマンドで取り込んでおいて

* `cd ファイルを置きたい場所`
* `git clone https://github.com/datsuns/yui_learning.git`

`yui_learning`っていうディレクトリが出来上がって、そこにファイルが出来上がるず。
以下の手順をやって、このタスクはdoneにしましょうか。

* hello.cを適当にいじって、
* `git add hello.c`
* `git commit -m'お好きなコメント'`
* `git push origin master`
* 変更した内容がgithubに適用されてること

**Comment by KuniakiY** [comment]
hello.cが無かったため(hello.c.cppしか残ってなかったです💦)、追加してプッシュしておきました。

**Comment by datsuns** [comment]
なんと！！ごめんごめん

**Comment by datsuns** [comment]
githubに放り込むのはもういけますな。クローズします。
